### ISSUE TITLE
Poder descargar el PDF desde la consulta con clave única

### ISSUE THREAD

**Issue by AquaroTorres** [cl-ssi/monitor#12]

**Comment by tebiccr** [comment]
Si se descarga tanto por el
Route::get('download/{file}','SuspectCaseController@download')->name('download')->middleware('auth');
o por 
Route::get('print/{suspect_case}','SuspectCaseController@print')->middleware('auth')->name('print');

Habría que quitar el middleware, dejando expuesta la ruta y pudiendo cualquier persona digitar un numero al azar en el navegador y ver examenes

**Comment by AquaroTorres** [comment]
Habría que ver si al cargar la página por primera vez, se puede hacer cargar el PDF embebido cosa de tenerlo en pantalla, quizás dentro de un div que se muestre a través de jQuery
