### ISSUE TITLE
Error cuando no existen casos positivos de sars_cov_2

### ISSUE THREAD

**Issue by Ukarus** [cl-ssi/monitor#3]
**Versión de Os**
Ubuntu Server 18.04
MariaDB 10.1.37

**Descripción**

Al acceder a la ruta "lab/suspect_cases/reports/positives" manda mensaje de error si no existen registros de casos sospechosos.

![Captura de pantalla de 2020-06-02 13-36-45](https://user-images.githubusercontent.com/23401478/83553003-95b85c00-a4d8-11ea-9e34-2f3474e17430.png)

Saludos, si necesitan ayuda estoy dispuesto a colaborar.

**Comment by AquaroTorres** [comment]
Hola, gracias por tu ayuda.
Desde ya bienvenido a colaborar.
Si no existe un caso positivo no puede establecer el primer dia de pandemia en la región, por lo tanto al agregar un caso, se soluciona, otro error es la población de las comunas, si no está definida divide por 0 para calcular la tasa de incidencia. En el fondo hace falta un par de IF en ambos casos.
