### ISSUE TITLE
erro migrate

### ISSUE THREAD

**Issue by maicolfedez** [cl-ssi/monitor#6]
hola, muchas gracias por tu contribución, estoy instalando el servidor en mi computador mac, pero al momento de migrar se arroja un error "file_put_contents(): Exclusive locks are not supported for this stream" usando sqlite, ahora igual cambio "LOCK_EX" por "LOCK_SH" y esta ves termina de migrar pero al loguear arroja un erro 419. espero puedan ayudarme, de ante mano gracias.

**Comment by AquaroTorres** [comment]
Hola, en un simple iteración, el problema es con sqlite, quizá el permiso de acceso a la base de datos y no algún problema con el sistema. La verdad es que no se me ocurre como ayudarte con eso. El error 419 no lo había visto nunca.
